version: "3.8"
services:
  flutter_dev:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - CHROME_EXECUTABLE=/usr/bin/chromium-browser
    stdin_open: true
    tty: true
