name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install      # o el comando que uses

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          organization: deviscoutb
          projectKey: AutomativeCompany
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
