name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Prepara Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '16'  # o la versión que uses

      # 2) Instala deps de backend si es necesario
      # Si tienes backend, instala sus dependencias. Aquí un ejemplo:
      # - name: Install backend dependencies
      #   run: npm install --prefix backend

      # 3) Instala deps de frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 4) Lanza el análisis de SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.organization=deviscoutb
            -Dsonar.projectKey=AutomativeCompany
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
